package com.zy.callinterceptor.pojo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table INTERCEPTOR_CONTACT.
 */
public class InterceptorContact {

    public static class Type{
        public final static int BLACK_LIST = 1;
        public final static int WHITE_LIST = 2;
    }

    private Long id;
    private String name;
    public String phoneNumber;
    private Integer groupId;
    private Integer type;
    private Integer timeRef;

    public InterceptorContact() {
    }

    public InterceptorContact(Long id) {
        this.id = id;
    }

    public InterceptorContact(Long id, String name, String phoneNumber, Integer groupId, Integer type, Integer timeRef) {
        this.id = id;
        this.name = name;
        this.phoneNumber = phoneNumber;
        this.groupId = groupId;
        this.type = type;
        this.timeRef = timeRef;
    }

    public InterceptorContact(String name, String phoneNum) {
        this.name = name;
        this.phoneNumber = phoneNum;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public Integer getGroupId() {
        return groupId;
    }

    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getTimeRef() {
        return timeRef;
    }

    public void setTimeRef(Integer timeRef) {
        this.timeRef = timeRef;
    }

}
