package com.zy.callinterceptor.dao;

import android.database.sqlite.SQLiteDatabase;

import com.zy.callinterceptor.pojo.InterceptorContact;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig interceptorContactDaoConfig;

    private final InterceptorContactDao interceptorContactDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        interceptorContactDaoConfig = daoConfigMap.get(InterceptorContactDao.class).clone();
        interceptorContactDaoConfig.initIdentityScope(type);

        interceptorContactDao = new InterceptorContactDao(interceptorContactDaoConfig, this);

        registerDao(InterceptorContact.class, interceptorContactDao);
    }
    
    public void clear() {
        interceptorContactDaoConfig.getIdentityScope().clear();
    }

    public InterceptorContactDao getInterceptorContactDao() {
        return interceptorContactDao;
    }

}
